name: Trigger auto deployment for ebgate

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - 'ui/**'
    - '.github/workflows/ebgate-AutoDeployTrigger-774609f6-a0c1-4081-927c-11bfa0a40be3.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.EBGATE_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.EBGATE_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.EBGATE_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/ui 
          registryUrl: cr4ebgate32407.azurecr.io
          registryUsername: ${{ secrets.EBGATE_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.EBGATE_REGISTRY_PASSWORD }}
          containerAppName: ebgate
          resourceGroup: rg-IndiaElectoralBonds
          imageToBuild: cr4ebgate32407.azurecr.io/ebgate:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


